version: 0.2

run-as: root

env:
  parameter-store:
            DB_PASSWORD: "/password"

phases:
   pre_build:
     commands:
       - apt update
       - apt upgrade -y
       - apt autoremove --purge
       - apt install nginx -y
       - apt install php php-fpm -y

   build:
     commands:
        - sed -i 's/password_here/'$DB_PASSWORD'/' wp-config.php
       

artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'


